package com.codered.engine.input;

import org.lwjgl.glfw.GLFW;

public enum Key
{
	A(GLFW.GLFW_KEY_A),
	B(GLFW.GLFW_KEY_B),
	C(GLFW.GLFW_KEY_C),
	D(GLFW.GLFW_KEY_D),
	E(GLFW.GLFW_KEY_E),
	F(GLFW.GLFW_KEY_F),
	G(GLFW.GLFW_KEY_G),
	H(GLFW.GLFW_KEY_H),
	J(GLFW.GLFW_KEY_J),
	K(GLFW.GLFW_KEY_K),
	L(GLFW.GLFW_KEY_L),
	M(GLFW.GLFW_KEY_M),
	N(GLFW.GLFW_KEY_N),
	O(GLFW.GLFW_KEY_O),
	P(GLFW.GLFW_KEY_P),
	Q(GLFW.GLFW_KEY_Q),
	R(GLFW.GLFW_KEY_R),
	S(GLFW.GLFW_KEY_S),
	T(GLFW.GLFW_KEY_T),
	U(GLFW.GLFW_KEY_U),
	V(GLFW.GLFW_KEY_V),
	W(GLFW.GLFW_KEY_W),
	X(GLFW.GLFW_KEY_X),
	Y(GLFW.GLFW_KEY_Y),
	Z(GLFW.GLFW_KEY_Z),
	
	NUMPAD_0(GLFW.GLFW_KEY_KP_0),
	NUMPAD_1(GLFW.GLFW_KEY_KP_1),
	NUMPAD_2(GLFW.GLFW_KEY_KP_2),
	NUMPAD_3(GLFW.GLFW_KEY_KP_3),
	NUMPAD_4(GLFW.GLFW_KEY_KP_4),
	NUMPAD_5(GLFW.GLFW_KEY_KP_5),
	NUMPAD_6(GLFW.GLFW_KEY_KP_6),
	NUMPAD_7(GLFW.GLFW_KEY_KP_7),
	NUMPAD_8(GLFW.GLFW_KEY_KP_8),
	NUMPAD_9(GLFW.GLFW_KEY_KP_9),

	NUM_0(GLFW.GLFW_KEY_0),
	NUM_1(GLFW.GLFW_KEY_1),
	NUM_2(GLFW.GLFW_KEY_2),
	NUM_3(GLFW.GLFW_KEY_3),
	NUM_4(GLFW.GLFW_KEY_4),
	NUM_5(GLFW.GLFW_KEY_5),
	NUM_6(GLFW.GLFW_KEY_6),
	NUM_7(GLFW.GLFW_KEY_7),
	NUM_8(GLFW.GLFW_KEY_8),
	NUM_9(GLFW.GLFW_KEY_9),
	
	UP(GLFW.GLFW_KEY_UP),
	DOWN(GLFW.GLFW_KEY_DOWN),
	LEFT(GLFW.GLFW_KEY_LEFT),
	RIGHT(GLFW.GLFW_KEY_RIGHT),
	
	ESCAPE(GLFW.GLFW_KEY_ESCAPE),
	SPACE(GLFW.GLFW_KEY_SPACE),
	
	INSERT(GLFW.GLFW_KEY_INSERT),
	DELETE(GLFW.GLFW_KEY_DELETE),
	HOME(GLFW.GLFW_KEY_HOME),
	END(GLFW.GLFW_KEY_END),
	PAGE_UP(GLFW.GLFW_KEY_PAGE_UP),
	PAGE_DOWN(GLFW.GLFW_KEY_PAGE_DOWN),
	TAB(GLFW.GLFW_KEY_TAB)
	;
	
	private final int id;
	
	private Key(int id)
	{
		
		this.id = id;
	}
	
	public int getId() { return this.id; }
	
	public Key getByIndex(int index)
	{
		return Key.values()[index];
	}
}
